### ISSUE TITLE
写的太笼统 需要考虑并发情况，考虑加锁解锁是不是自己的

### ISSUE THREAD

**Issue by saibanCFY** [hutu92/distributed-lock#1]
public class RedisTool {
    private static final String LOCK_SUCCESS = "OK";
   private static final String SET_IF_NOT_EXIST = "NX";
    private static final String SET_WITH_EXPIRE_TIME = "PX";
    /**
   * 尝试获取分布式锁
    * @param jedis Redis客户端
    * @param lockKey 锁
    * @param requestId 请求标识
    * @param expireTime 超期时间
     * @return 是否获取成功
     */
   public static boolean tryGetDistributedLock(Jedis jedis, String lockKey, String requestId, int 
        expireTime) {
        String result = jedis.set(lockKey, requestId, SET_IF_NOT_EXIST, SET_WITH_EXPIRE_TIME, 
        expireTime);
       if (LOCK_SUCCESS.equals(result)) {
           return true;
      }
       return false;
    }
}
/**
     * 释放分布式锁
     * @param jedis Redis客户端
     * @param lockKey 锁
    * @param requestId 请求标识
     * @return 是否释放成功
     */
    public static boolean releaseDistributedLock(Jedis jedis, String lockKey, String requestId) {
       String script = "if redis.call('get', KEYS[1]) == ARGV[1] then return redis.call('del', KEYS[1]) else 
       return 0 end";
        Object result = jedis.eval(script, Collections.singletonList(lockKey), 
        Collections.singletonList(requestId));
        if (RELEASE_SUCCESS.equals(result)) {
            return true;
        }
        return false;
    }
}

**Comment by hutu92** [comment]
正确的实现：
[/v2/DistributedLock.java](https://github.com/hutu92/distributed-lock/tree/master/src/main/java/com/github/hutu92/concurrent/locks/v2)

```java
Lock cLock = lockThreadLocal.get();
```

1. 这段代码就是用来确认释放的锁是不是自己的。

你贴的那段代码不是我的实现呀，你那段代码使用起来是很不友好的，很可能传入错误的参数，导致释放别的线程获取的锁。

2. 并发方面可能会存在**redis性能瓶颈**。但是这是最简单的实现方式，一般并发场景下足够了，如果是高并发场景，这个锁是存在问题的。

3. 锁的重入和读写锁，实现起来在分布式场景下更复杂。这里就不考虑了。
